.pip_install:
  before_script:
    - pip install requests
    - pip install svn
    - pip install redis

stages:
  - build
  - package

build-linux:
  stage: build
  tags:
    - centos8 python3
  only:
    - master
  extends: .pip_install
  script:
    - cd IncrementalPackageCheck
    - mkdir -p bin/linux

    - pyinstaller -F update_single_number.py
    - cp dist/testagain bin/linux/update_single_number

    - pyinstaller -F update_redis.py
    - cp dist/update_redis bin/linux/update_redis

  artifacts:
    name: linux
    paths:
      - IncrementalPackageCheck/bin/linux

build-mac:
  stage: build
  tags:
    - mac python3
  only:
    - master
  extends: .pip_install
  script:
    - cd IncrementalPackageCheck
    - mkdir -p bin/mac

    - pyinstaller -F update_single_number.py
    - cp dist/testagain bin/mac/update_single_number

    - pyinstaller -F update_redis.py
    - cp dist/update_redis bin/mac/update_redis

  artifacts:
    name: mac
    paths:
      - IncrementalPackageCheck/bin/mac

build-windows:
  stage: build
  tags:
    - windows10 python3
  only:
    - master
  extends: .pip_install
  script:
    - cd IncrementalPackageCheck
    - mkdir -p bin/windows

    - pyinstaller -F update_single_number.py
    - cp dist/testagain.exe bin/windows/update_single_number.exe

    - pyinstaller -F update_redis.py
    - cp dist/update_redis.exe bin/windows/update_redis.exe

  artifacts:
    name: windows
    paths:
      - IncrementalPackageCheck/bin/windows

package-bin:
  stage: package
  tags:
    - centos8 python3
  only:
    - master
  needs: ["build-linux", "build-mac", "build-windows"]
  script:
    - ls IncrementalPackageCheck/bin
  artifacts:
    name: all
    paths:
      - IncrementalPackageCheck/bin

