.pip_install:
  before_script:
    - pip install requests

stages:
  - build
  - package

build-linux:
  stage: build
  tags:
    - centos8 python3
  only:
    - master
  extends: .pip_install
  script:
    - cd IncrementalPackageCheck
    - mkdir -p bin/linux

    - pyinstaller -F testagain.py
    - cp dist/testagain bin/linux/testagain

  artifacts:
    name: linux
    paths:
      - IncrementalPackageCheck/bin/linux

build-mac:
  stage: build
  tags:
    - mac python3
  only:
    - master
  extends: .pip_install
  script:
    - cd IncrementalPackageCheck
    - mkdir -p bin/mac

    - pyinstaller -F testagain.py
    - cp dist/testagain bin/mac/testagain

  artifacts:
    name: mac
    paths:
      - IncrementalPackageCheck/bin/mac

build-windows:
  stage: build
  tags:
    - windows10 python3
  only:
    - master
  extends: .pip_install
  script:
    - cd IncrementalPackageCheck
    - mkdir -p bin/windows

    - pyinstaller -F testagain.py
    - cp dist/testagain.exe bin/windows/testagain.exe


  artifacts:
    name: windows
    paths:
      - IncrementalPackageCheck/bin/windows

package-bin:
  stage: package
  tags:
    - centos8 python3
  only:
    - master
  needs: ["build-linux", "build-mac", "build-windows"]
  script:
    - ls IncrementalPackageCheck/bin
  artifacts:
    name: all
    paths:
      - IncrementalPackageCheck/bin

